### ISSUE TITLE
Vector arrow not shown

### ISSUE THREAD

**Issue by obiscr** [3b1b/manim#2224]
### Describe the bug

Vector arrows not displaying properly as expected.

I integrated Latex in the astro project.

**package.json**
```json
"dependencies": {
    ...
    "rehype-katex": "^7.0.1",
    "remark-math": "^6.0.0",
    ...
  },
```

**astro.config.ts**
```ts
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";

// https://astro.build/config
export default defineConfig({
	...
	markdown: {
		// Override with our own config
		smartypants: false,
		remarkPlugins: [
			[remarkSmartypants, { dashes: false }],
			// Add our custom plugin that marks links to fallback language pages
			remarkFallbackLang(),
			remarkMath,
		],
		rehypePlugins: [
			rehypeSlug,
			// This adds links to headings
			...rehypeAutolink(),
			// Tweak GFM task list syntax
			rehypeTasklistEnhancer(),
			rehypeKatex,
		],
	},
        ...
});

```

**Code**:

In Footer component

```
---
import DefaultFooter from '@astrojs/starlight/components/Footer.astro';
import FooterLinks from '../FooterLinks.astro';
import type { Props } from '@astrojs/starlight/props';
---

<DefaultFooter {...Astro.props} />
<FooterLinks />
<!--Katex-->
<link
	rel="stylesheet"
	href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
	integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
	crossorigin="anonymous"
/>
<script
	defer
	src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"
	integrity="sha384-XjKyOOlGwcjNTAIQHIpgOno0Hl1YQqzUOEleOLALmuqehneUG+vnGctmUb0ZY0l8"
	crossorigin="anonymous"
></script>
<script
	defer
	src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"
	integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05"
	crossorigin="anonymous"
	onload="renderMathInElement(document.body);"
></script>

```

**Wrong display or Error traceback**:

No error traceback found

### Additional context

```html
<span class="accent-body" style="left:-0.1522em;">
</span>
```

I found this class, which has the default style

```css
element.style {
    left: -0.1522em;
}

.katex .accent .accent-body:not(.accent-full) {
    width: 0;
}

.katex .accent .accent-body {
    position: relative;
}

.katex .vlist>span>span {
    display: inline-block;
}

.katex * {
    -ms-high-contrast-adjust: none !important;
    border-color: currentColor;
}
```

I found that once I used the following custom style to rewrote the default style, the arrows were displayed correctly

```css
.katex .accent .accent-body:not(.accent-full) {
    width: 9px !important;
}

.katex .accent .accent-body {
    left: 0 !important;
}
```
I hope this information is useful
