### ISSUE TITLE
custom_config not working

### ISSUE THREAD

**Issue by GarrickLin** [3b1b/manim#2239]
### Describe the error
- I created a `custom_config.yml` in the same folder, and filled in some params (changed background color)
- run `manimgl animation.py HelloLaTeX`

### Code and Error

`custom_config.yml`  

```yaml
break_into_partial_movies: false
camera_resolutions:
  4k: 3840x2160
  default_resolution: high
  high: 1920x1080
  low: 854x480
  medium: 1280x720
directories:
  mirror_module_path: false
fps: 30
full_screen: false
style:
  background_color: "#1e4b31"
  font: Consolas
  tex_template: default
universal_import_line: from manimlib import *
window_monitor: 0
window_position: UR
tex:
  text_to_replace: [tex_expression]
  executable: xelatex -no-pdf
  template_file: ctex_template.tex
  intermediate_filetype: xdv
```

`animation.py`

```python
from manimlib import *


class HelloLaTeX(Scene):
    def construct(self):
        self.ss = r"$ax^2+bx+c$"
        tex = TexText(self.ss, font_size=144)
        self.add(tex)

```
The background color has not changed(still black), and it did not support Chinese.

I logged the intermediate latex command like:

```
latex -interaction=batchmode -halt-on-error -output-directory="/var/folders/7y/1j0kg1lj6q94pm_zzzjvxtjh0000gn/T/Tex" "/var/folders/7y/1j0kg1lj6q94pm_zzzjvxtjh0000gn/T/Tex/e9f7d5d816f0514a.tex"
```
which did not invoke `xelatex -no-pdf` as config file required.

### Environment
**OS System**:  macOS m1
**manim version**:  1.7.1

```
Name: manimgl
Version: 1.7.1
Summary: Animation engine for explanatory math videos
Home-page: https://github.com/3b1b/manim
Author: Grant Sanderson
Author-email: grant@3blue1brown.com
License: MIT
Location: /Users/garrick/anaconda3/envs/manim/lib/python3.10/site-packages
Requires: colour, fontTools, ipython, isosurfaces, manimpango, mapbox-earcut, matplotlib, moderngl, moderngl-window, numpy, Pillow, pydub, pygments, PyOpenGL, pyperclip, pyyaml, rich, scipy, screeninfo, skia-pathops, svgelements, sympy, tqdm, typing-extensions, validators
Required-by: 
```

**python version**: Python 3.10.15
