### ISSUE TITLE
No module named manim

### ISSUE THREAD

**Issue by ItsPlantseed** [3b1b/manim#483]
After I updated manim to the latest version, whenever I try to run:
`python3 -m manim example_scenes.py SquareToCircle -pl` 
It will return as: `/usr/local/bin/python3: No module named manim`.

Full code:
```
PS C:\Users\User\Downloads\Manim> docker run -itv C:\Users\USER\Downloads\Manim:/root/manim eulertour/manim
root@f4b2d3c43ad7:~# cd manim
root@f4b2d3c43ad7:~/manim# python3 -m manim example_scenes.py SquareToCircle -pl
/usr/local/bin/python3: No module named manim
```

I'm using Docker,  and I have already pulled the latest version.

**Comment by eulertour** [comment]
Sorry, I haven't been giving the dockerfile as much attention as I ought to. Try passing `-e PYTHONPATH=/root/manim` to `docker run`.

**Comment by ItsPlantseed** [comment]
You mean together like this?
`docker run -e C:\Users\USER\AppData\Local\Programs\Python\Python37-32\=/root/manim -itv C:\Users\USER\Downloads\Manim:/root/manim eulertour/manim`

**Comment by eulertour** [comment]
No, just the way I typed it above. The environment variable needs to be set in the container, so it won't change based on your system.

**Comment by ItsPlantseed** [comment]
Now it outputs me this:
```
PS C:\Users\User\Downloads\Manim> docker run -e C:\Users\USER\AppData\Local\Programs\Python\Python37-32\=/root/manim manim
PS C:\Users\User\Downloads\Manim> docker run -itv C:\Users\USER\Downloads\Manim:/root/manim eulertour/manim
root@ea83d3837c81:~# python3 -m manim example_scenes.py SquareToCircle -pl
/usr/local/bin/python3: No module named manim.__main__; 'manim' is a package and cannot be directly executed
root@ea83d3837c81:~#         
```

I cannot do plain  ``docker run -e C:\Users\USER\AppData\Local\Programs\Python\Python37-32\=/root/manim`` though, it requires the image argument.

**Comment by eulertour** [comment]
Try following the new docker instructions using `docker-compose` and let me know if you encounter any problems.

**Comment by ItsPlantseed** [comment]
I'm confused at this line:
`MANIM_PATH=/absolute/path/to/manim/repo docker-compose run manim example_scenes.py SquareToCircle -l`
Am I supposed to type exactly like that? Also should I set the environment variables using `docker run -e MANIM_PATH=C:/Users/User/Downloads/Manim eulertour/manim` or is there another way?

**Comment by yoshiask** [comment]
Windows tends to not play nicely with the `-m` flag. If I'm not mistaken, that flag is not necessary to run the script.

Try `python3 example_scenes.py SquareToCircle -pl` in Command Prompt. (Make sure you're in the manim folder.)

**Comment by ItsPlantseed** [comment]
> Windows tends to not play nicely with the `-m` flag. If I'm not mistaken, that flag is not necessary to run the script.
> 
> Try `python3 manim.py example_scenes.py SquareToCircle -pl` in Command Prompt. (Make sure you're in the manim folder.)

That didn't do anything.

**Comment by eulertour** [comment]
The intention is to set the `MANIM_PATH` environment variable to the absolute path to your manim repo. However, I'm not sure how to do that with Windows.

**Comment by ItsPlantseed** [comment]
So I messed around with the docker-compose.yml file and changed the version to "3.2":
```
version: '3.2'

services:
  manim:
    # comment this line if you build the image to prevent overwriting the tag
    # image: eulertour/manim:latest
    # uncomment this line to build rather than pull the image
    build: .
    volumes:
      - ${MANIM_PATH=?MANIM_PATH environment variable isn't set}:
      - MANIM_PATH=C:/Users/User/Downloads/Manim
    environment:
      - PYTHONPATH=C:/Users/USER/AppData/Local/Programs/Python/Python37-32/
    working_dir: /opt/manim
    entrypoint:
      - python
      - -m
      - manim
    network_mode: "none"
```

And now it outputs:
```
PS C:\Users\User\Downloads\Manim> docker-compose run manim example_scenes.py SquareToCircle -l
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.manim.volumes 'type' is a required property
```
Maybe I'm going in the right direction with this. 
Also do I need to change whatever `PYTHON_PATH` value is and what's about the `working_dir`?
